#baseurl = "http://cogell.com/blog"
languageCode = "en-us"
title = "Some Thoughts"
paginate = 5
DisquaShortname = "cogell"
#canonifyurls = true

[params]
  description = "mistakes are encouraged"
  cover = "media/messy-architecture-desk.jpg"
  author = "B. Cedric Cogell"
  authorlocation = "Hudson Valley, New York"
  bio = "Software Engineer, reader, friend, and human"
  logo = ""
  githubName = "cogell"
  twitterName = "cogell"
