baseurl = "http://blog.cogell.com/"
languageCode = "en-us"
title = "Some Thoughts"
paginate = 5
DisquaShortname = "cogell"
#canonifyurls = true

[params]
  description = "mistakes are encouraged"
  cover = "media/messy-architecture-desk.min.jpg"
  author = "B. Cedric Cogell"
  authorlocation = "Hudson Valley, New York"
  bio = "Software Engineer, reader, friend, and human"
  logo = "media/logo.png"
  githubName = "cogell"
  twitterName = "cogell"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
